FROM arm32v7/node:16.3.0

RUN apt-get update -y && apt-get install -y apt-utils tzdata && apt-get install fswebcam ffmpeg -y && apt-get install mpg123 -y && apt-get install vim -y

WORKDIR /server

COPY . /server

RUN npm install -g npm
RUN npm install
RUN npm run build

VOLUME /mms_shared_volume
EXPOSE 3000

CMD [ "npm", "start" ]