FROM alpine:3.10
RUN apk add --no-cache  --update nodejs-current npm curl bash procps tzdata
RUN node --version
RUN npm --version

ENV TZ="America/New_York"

WORKDIR /server

COPY . /server

RUN npm install -g npm
RUN npm install
RUN npm run build

VOLUME /mms_shared_volume
EXPOSE 3000

CMD [ "npm", "start" ]