# This workflow will do a clean install of node dependencies and build the source code of Liquid Prep backend service for node version 14.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Liquid Prep Backend Actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_backend_service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Install Node dependencies for common folder
        run: |
          cd common
          npm install
          cd ../
      - name: Install Node dependencies for cloud functions and build
        run: |
          cd liquid-prep-cf
          npm install
          npm run build
          npm run bundle
